id: P007073
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17586
  title: བདེ་ཆོག་ནག་པོའི་སྒྲུབ་དཀྱིལ།
  author: ''
  volumes:
    d073ffa1aba2456484404165fba0af4c:
      image_group_id: I1KG17957
      title: ''
      volume_number: 1
      total_pages: 258
ebook_metadata:
  title: བདེ་ཆོག་ནག་པོའི་སྒྲུབ་དཀྱིལ།
  author: ''
  sku: P007073
  cover: cover.jpg
  layers:
  - pagination
