id: P007073
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG17586
  title: བདེ་ཆོག་ནག་པོའི་སྒྲུབ་དཀྱིལ།
  author: ''
  volumes:
    cec85f0ac70145bc99269136c1234580:
      image_group_id: I1KG17957
      title: Volume 1 of bde chog nag po'i sgrub dkyil/
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
