id: I642B6BDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:28:28+00:00'
last_modified: '2022-06-09T04:34:47.683059+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17586
  title: བདེ་ཆོག་ནག་པོའི་སྒྲུབ་དཀྱིལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A7A9:
      image_group_id: I1KG17957
      title: Volume 1 of bde chog nag po'i sgrub dkyil/
      total_pages: 258
      order: 1
      base_file: A7A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
